pa= float ( input ( "\n\tEnter Principal Amount :" ))
ri= float ( input ( "\n\tEnter Rate Of Interest. :" ))
year= float ( input ( "\n\tEnter Number of Year. :" ))
interest= float (ri/ 100 *pa*year)
print ( "\n\tPrincipal Amount : Rs." ,pa)
print ( "\n\tRate of Interest :" ,ri, "%" )
print ( "\n\tNumber of Years :" ,year)
print ( "\n\tSimpleInterest : Rs." ,interest)
print ( "\n\tMaturity Amount : Rs." ,interest+pa)